---
title: "AdoLong"
author: "Livio Finos"
date: '15-16 July 2024'
output: 
  html_document: 
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read Data

Dataset:

Talking about the Birth Family since the Beginning: The Communicative Openness in the New Adoptive Family
Santona, A., Tognasso, G., Miscioscia, C.L., Russo, D., Gorla, L.
International Journal of Environmental Research and Public Health, 2022, 19(3), 1203

```{r}
#library(haven)
library(tidyr)
library(lmerTest)
library(effects)
library(sjPlot)
library(ggplot2)
theme_set(theme_sjplot())

load(file="adolong.Rdata")
adolong=(na.omit(adolong[,c("SALUTE","GENERE","TIME","ETA_B_ARRIVO","PROV_BAMB","SOGG","COMP_ESTERN")]))

summary(adolong)

```

# Data Visualization

```{r}
dataplot <- aggregate(x = adolong$SALUTE, 
                               by = list(Time=adolong$TIME,Country=adolong$PROV_BAMB), 
                               FUN = function(x){
                                 # print(x);
                                 # browser();
                                x=as.numeric(as.character(x));
 res=c(prop=mean(x),sd=sd(x),n=length(x))})
  
  dataplot=cbind(dataplot[,1:2],dataplot$x)
  dataplot$upper=dataplot$prop+dataplot$sd/sqrt(dataplot$n)
  dataplot$lower=dataplot$prop-dataplot$sd/sqrt(dataplot$n)
    require(ggplot2)
  pd <- position_dodge(width = 2)
  GP=ggplot(data=dataplot, aes(x=Time, y=prop, group=Country,colour=Country)) + 
    geom_line( size=1.5)+geom_errorbar(data=dataplot, mapping=aes(x=Time, ymin=upper, ymax=lower), position=pd, width=0.2, size=1, color="grey",alpha=.5)
  print(GP)  
  
  ###################
  dataplot <- aggregate(x = adolong$COMP_ESTERN, 
                               by = list(Time=adolong$TIME,Country=adolong$PROV_BAMB), 
                               FUN = function(x){
                                 # print(x);
                                 # browser();
                                x=as.numeric(as.character(x));
 res=c(prop=mean(x),sd=sd(x),n=length(x))})
  
  dataplot=cbind(dataplot[,1:2],dataplot$x)
  dataplot$upper=dataplot$prop+dataplot$sd/sqrt(dataplot$n)
  dataplot$lower=dataplot$prop-dataplot$sd/sqrt(dataplot$n)
    require(ggplot2)
  pd <- position_dodge(width = 2)
  GP=ggplot(data=dataplot, aes(x=Time, y=prop, group=Country,colour=Country)) + 
    geom_line( size=1.5)+geom_errorbar(data=dataplot, mapping=aes(x=Time, ymin=upper, ymax=lower), position=pd, width=0.2, size=1, color="grey",alpha=.5)
  print(GP)  
  
```


# Inference

```{r}


library(lmerTest)

mod1=glmer(SALUTE~GENERE*TIME+ETA_B_ARRIVO+PROV_BAMB+(1+TIME|SOGG),data=adolong,family=binomial,control=glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e5)))

summary(mod1)  
car::Anova(mod1)
print(plot_model(mod1, type = "pred", terms = c("ETA_B_ARRIVO")))
print(plot_model(mod1, type = "pred", terms = c(("TIME"), ("GENERE"))))
print(plot_model(mod1, type = "pred", terms = c("PROV_BAMB")))

##########

mod2=glmer(COMP_ESTERN~GENERE*TIME+ETA_B_ARRIVO+PROV_BAMB+(1+TIME|SOGG),data=adolong,family=binomial,control=glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e5)))

summary(mod2)  
car::Anova(mod2)
print(plot_model(mod2, type = "pred", terms = c("ETA_B_ARRIVO")))
print(plot_model(mod2, type = "pred", terms = c(("TIME"), ("GENERE"))))
print(plot_model(mod2, type = "pred", terms = c("PROV_BAMB")))
```


## Permutation approach 

```{r}

library(tidyverse)
dati1lev=adolong %>% 
  group_by(SOGG) %>%
  reframe(estim=(coefficients(glm(SALUTE~TIME,family=binomial))))
dati1lev$coeff=(rep(c("Interc","Slope"),nrow(dati1lev)/2))


temp=adolong %>%select(-c(TIME,SALUTE,COMP_ESTERN)) %>%
  group_by(SOGG) %>%
  unique()


library(tidyr)
dati1lev=spread(dati1lev, key = coeff, value = estim)
dati1lev=left_join(dati1lev,temp)

head(dati1lev)

###############plots

p <- ggplot(dati1lev,aes(PROV_BAMB,Interc,color=PROV_BAMB))
p+geom_point(size = 3) +geom_boxplot(alpha=.1)


p <- ggplot(dati1lev,aes(PROV_BAMB,Interc,color=PROV_BAMB))
p+geom_point(size = 3) +geom_boxplot(alpha=.1)


library(flipscores)

#Testing Intercept and any main effect between subjects:
res=flipscores(Interc~GENERE+PROV_BAMB+ETA_B_ARRIVO,data=dati1lev)
summary(res)
anova(res)


#Testing Time
res=flipscores(Slope~1,data=dati1lev)
summary(res)
#Testing Time and interactions between Time and any within subject effects
(res=flipscores(Slope~GENERE+PROV_BAMB+ETA_B_ARRIVO,data=dati1lev))
summary(res)
anova(res)

```

### An alternative

```{r}
library(logistf)

library(tidyverse)
dati1lev=adolong %>% 
  group_by(SOGG) %>%
  reframe(estim=(coefficients(logistf(SALUTE~TIME,family= binomial(link="logit")))))
dati1lev$coeff=(rep(c("Interc","Slope"),nrow(dati1lev)/2))


temp=adolong %>%select(-c(TIME,SALUTE,COMP_ESTERN)) %>%
  group_by(SOGG) %>%
  unique()


library(tidyr)
dati1lev=spread(dati1lev, key = coeff, value = estim)
dati1lev=left_join(dati1lev,temp)

head(dati1lev)

###############plots

p <- ggplot(dati1lev,aes(PROV_BAMB,Interc,color=PROV_BAMB))
p+geom_point(size = 3) +geom_boxplot(alpha=.1)


p <- ggplot(dati1lev,aes(PROV_BAMB,Interc,color=PROV_BAMB))
p+geom_point(size = 3) +geom_boxplot(alpha=.1)


library(flipscores)

#Testing Intercept and any main effect between subjects:
res=flipscores(Interc~GENERE+PROV_BAMB+ETA_B_ARRIVO,data=dati1lev)
summary(res)
anova(res)


#Testing Time
res=flipscores(Slope~1,data=dati1lev)
summary(res)
#Testing Time and interactions between Time and any within subject effects
(res=flipscores(Slope~GENERE+PROV_BAMB+ETA_B_ARRIVO,data=dati1lev))
summary(res)
anova(res)

```

