---
title: "da scrambled experiment (maffei)"
output: html_document
date: "2025-01-12"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# library(readr)
# 
# file_list=dir("ERPDataSingleTrialforstudents",full.names = TRUE)
# temp=lapply(file_list,read_table)
# 
# str(temp)
# D=do.call(rbind,temp)
# 
# D = D[,c("PO7", "PO8","ID", "Condition")]
# 
# ##equivalent to:
# #library(dplyr)
# ##select columns by name
# #D = D %>%  select(PO7, PO8,ID, Condition)
# 
# library(tidyr)
# 
# # The arguments to gather():
# # - data: Data object
# # - key: Name of new key column (made from names of data columns)
# # - value: Name of new value column
# # - ...: Names of source columns that contain values
# # - factor_key: Treat the new key column as a factor (instead of character vector)
# D <- gather(D, Channel, Mean_Amplitude, PO7:PO8,factor_key=TRUE)
# 
# write_csv(D,file = "data_eeg_scrambled.csv")

library(readr)
D=read.csv("data_eeg_scrambled.csv",stringsAsFactors = TRUE)
str(D)

```



# Fit a model
```{r}
contrasts(D$Channel)=contr.sum

# Fit the mixed modelcontr.sum()# Fit the mixed model
model <- lmer(Mean_Amplitude ~ Condition * Channel + (0+Condition|ID)+(0+Channel|ID), data = D)

# Model summary
summary(model)

# ANOVA of the model
car::Anova(model)


# Post-hoc analysis using emmeans
emmeans_result <- emmeans(model, pairwise ~ Condition | Channel)
summary(emmeans_result)

```

## Plotting tools

for the first model:
```{r message=FALSE}
library(effects)
plot(allEffects(model))

#plot random effects:
require(lattice)
qqmath(ranef(model, condVar=TRUE))
```

An alternative plotting tool:

```{r message=FALSE}
library(sjPlot)
library(ggplot2)
plot_model(model, type = "pred", terms = c("Condition", "Channel"))+theme_bw()
```

